# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  encoding: utf8
  #database: vader_dev
  #username: paul.rushby
  #host: swnatm16
  #password: Costa
  reconnect: true
  host: localhost
  database: unicodes
  username: root
  password: 
    
production:
  adapter: mysql2
  encoding: utf8
  #database: vader_dev
  #username: paul.rushby
  #host: swnatm16
  #password: Costa
  reconnect: true
  host: localhost
  database: unicodes
  username: root
  password:
